### ISSUE TITLE
Problems with Trellis 0.9.6

### ISSUE THREAD

**Issue by valentinocossar** [hamedb89/trellis-db-push-and-pull#1]
Hi, I'm using Trellis 0.9.6 on an old project, and with the hosts configuration provided by this playbook I can't reprovision the server, even the local vagrant.
This is the ansible output:
![screenshot](https://cloud.githubusercontent.com/assets/4087384/26065954/b84b1d4a-3995-11e7-8408-2b4ee781e3e6.png)
Which version of Trellis are you using or which version have you tested with this playbook? Thank you.

**Comment by hamedb89** [comment]
Hey, I haven't tried any dedicated testing, but from the error message it seems like the staging host file is either not executable or there is something going on with the syntax.

**Comment by valentinocossar** [comment]
Yes, but the file is executable, the problem is that I can't declare staging/production/development host IP with the syntax provided in the README of this project.

```
staging 234.234.234.234

[staging]
staging

[web]
staging
```

This not working for me and return me the error reported in the screenshot above.

```
staging ansible_host=234.234.234.234

[staging]
staging

[web]
staging
```

I'm also trying to use this syntax to declare the IP, but this generates another error that prevents the script from connecting via SSH into the vagrant with the vagrant user and finding the folder /srv/www/example.com/current.

![error](https://cloud.githubusercontent.com/assets/4087384/26105844/0ea11b6e-3a44-11e7-95b8-622ff0ec89a9.png)

Do you know any other way to set hostnames for every environment, different from the one provided by the README of this project?

**Comment by hamedb89** [comment]
You are right. The README is incomplete.

You need to add more variables to the staging host file. I will add this to the readme asap.

ps: i am not sure if ansible_ssh_private_key_file is necessary or at least used by ansible.

```
vagrant ansible_host=192.168.50.5 ansible_connection=ssh ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key

[development]
vagrant

[web]
vagrant
```

**Comment by valentinocossar** [comment]
Thank you! Do I have to add these variables in the staging or development host file? 🙂

**Comment by hamedb89** [comment]
I updated the readme. These variables should be added to development. 👍
