### ISSUE TITLE
url_from and url_to aren't working if you have more than one site hosted with a single Trellis machine

### ISSUE THREAD

**Issue by valentinocossar** [hamedb89/trellis-db-push-and-pull#2]
Hi, as I wrote in the issue title, these two variables (utl_from and url_to) aren't using {{ site }} variable to identify the wordpress_sites configuration of which you want to get the URL.

```
url_from: "{{ from_host.wordpress_sites.values().0.site_hosts.0.canonical }}"
url_to: "{{ hostvars.vagrant.wordpress_sites.values().0.site_hosts.0.canonical}}"
```

How can we make this more dynamic? Unfortunately, this isn't possible and return, obviously, an error.

```
url_from: "{{ from_host.wordpress_sites.values().{{ site }}.site_hosts.0.canonical }}"
url_to: "{{ hostvars.vagrant.wordpress_sites.values().{{ site }}.site_hosts.0.canonical}}"
```

Could you help me in some way? Thank you.

**Comment by hamedb89** [comment]
You would have to use values()[{{ site }}] instead but I am not sure if that works syntactically.however if you save the returned value of the values() function you could access it like then access it like an array.

Does that make sense?

**Comment by valentinocossar** [comment]
Yes, this fixed the problem:

```
url_from: "{{ from_host.wordpress_sites[site].site_hosts.0.canonical }}"
url_to: "{{ hostvars.development.wordpress_sites[site].site_hosts.0.canonical }}"
```

Thank you 👍
